version: '2'

services:
  glpi:
    build: .
    env_file:
      - ./glpi.env
# image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - glpi_data:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql

  php:
#    image: php:7-fpm-alpine
    build: php
    volumes:
      - glpi_data:/code
      - mysql_socket:/var/run/mysqld/
    links:
      - mysql

  mysql:
    image: mariadb
    env_file:
      - ./glpi.env
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_socket:/var/run/mysqld/

volumes:
  mysql_data: {}
  glpi_data: {}
  mysql_socket: {}
