version: '2'

services:
  glpi:
    build: glpi
    env_file:
      - ./glpi/glpi.env
    ports:
      - "80:80"
    volumes:
      - glpi_code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql

  php:
    build: php
    volumes:
      - glpi_code:/code
    links:
      - mysql

  mysql:
    env_file:
      - ./glpi/glpi.env
    build:
      context: mysql
    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
  glpi_code: {}
  glpi_data: {}
